chore: update vue api doc to match implementation
testing-library/testing-library-docs pull request #1141
Opened 2022-08-16 20:04 UTC by davidnixon

Fix for https://github.com/testing-library/vue-testing-library/issues/280

2022-08-16 20:46 UTC, timdeschryver approved these changes

2022-08-17 07:45 UTC, afontcu requested changes
thank you for this!! 🙌  I left some comments here and there

2022-08-17 07:45 UTC, afontcu commented on docs/vue-testing-library/api.mdx
> +[update properties example](vue-testing-library/examples.mdx#example-updating-properties).
see comment below

```suggestion
```

2022-08-17 07:45 UTC, afontcu commented on docs/vue-testing-library/api.mdx
> -#### `debug(element)`
debug still accepts an element:

https://github.com/testing-library/vue-testing-library/blob/main/src/render.js#L42

2022-08-17 07:45 UTC, afontcu commented on docs/vue-testing-library/api.mdx
>  Library.
there's a sentence below this one that says:

"It takes up to 3 parameters and returns an object with some helper methods."

it should be

"It takes up to 2 parameters and returns an object with some helper methods."

2022-08-17 16:55 UTC, afontcu approved these changes
thank you! 🤩

2022-08-17 16:56 UTC, merged

2022-08-17 16:56 UTC, afontcu commented
@all-contributors please add @davidnixon for docs