docs: update Vitest instructions for jest-dom
testing-library/testing-library-docs pull request #1229
Opened 2023-03-08 09:40 UTC by unikitty37

Add instructions on how to configure Vitest to import @testing-library/jest-dom automatically, to match the Vite instructions at 6.2.

2023-03-08 18:44 UTC, timdeschryver approved these changes

2023-03-08 18:45 UTC, timdeschryver commented on docs/svelte-testing-library/setup.mdx
> +    To have Vitest import this automatically in _every_ test file, add the import statement to a new file, then add the file to the `setupFiles` array in the `vitest.config.ts` (in this case, the fil
Maybe this should be added under 5.3 ?

2023-03-09 16:38 UTC, eps1lon requested changes
Why would you use a library specifically for Jest in Vitest? We already have an assertion library specifically for Vitest called `vitest-dom`. Could we clarify first if the folks at `@testing-library/jest-dom` want to support Vitest in addition to Jest?

2023-03-09 16:44 UTC, unikitty37 commented
> Why would you use a library specifically for Jest in Vitest? We already have an assertion library specifically for Vitest called [`vitest-dom`](https://github.com/chaance/vitest-dom). Could we clarify first if the folks at `@testing-library/jest-dom` want to support Vitest in addition to Jest?

I was just updating the current documentation, which uses jest-dom. I didn't even know about `vitest-dom` — but it doesn't seem to be compatible with the current vitest version:

```
╰─▷ npm i -D vitest-dom
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.0.1
npm ERR! Found: vitest@0.25.8
npm ERR! node_modules/vitest
npm ERR!   dev vitest@"~0.25.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vitest@"^0.16.0" from vitest-dom@0.0.4
npm ERR! node_modules/vitest-dom
npm ERR!   dev vitest-dom@"*" from the root project
```

2023-04-06 14:04 UTC, unikitty37 commented
Since `vitest-dom` doesn't work with current vitest, and my comment pointing this out doesn't seem to have resulted in any response, I'm going to assume this contribution is unwanted at this point.

2023-04-06 14:04 UTC, closed without merging