Add Vitest cleanup hint to react-testing-library setup docs
testing-library/testing-library-docs pull request #1422
Opened 2024-09-12 07:11 UTC by ezzatron

This PR adds a heading to the setup guide for `react-testing-library` that explains how to get auto-cleanup working when using Vitest. The wording was inspired by a similar heading in the `vue-testing-library` setup guide: https://testing-library.com/docs/vue-testing-library/setup/#vitest

2024-09-13 08:01 UTC, eps1lon requested changes
This should explain how to build auto-cleanup by yourself i.e. what do you do if you don't want to enable globals

2024-09-13 08:42 UTC, ezzatron commented
I had a crack at documenting how to get it working without enabling globals. Let me know what you think.

2024-12-10 23:21 UTC, ezzatron commented
Just following up to ask if there's anything else needed to progress this PR?

2024-12-11 07:26 UTC, MatanBobi approved these changes
Thanks!

2024-12-11 07:27 UTC, merged

2024-12-11 07:27 UTC, MatanBobi commented
@all-contributors please add @ezzatron for docs :)