Added Formik Recipe
testing-library/testing-library-docs pull request #640
Opened 2020-10-10 21:40 UTC by luistak

**What** 

Added a basic async Formik example test recipe based in [this example](https://formik.org/docs/examples/async-submission  as requested in #536

2020-10-24 17:05 UTC, luistak commented
Is this PR good to go?

2020-11-10 17:28 UTC, nickmccurdy requested changes

2020-11-10 17:28 UTC, nickmccurdy commented on website/sidebars.json
> +      "example-react-formik",
If we move this after`useReducer`, the React core examples will be grouped before the third party library examples.

2020-11-10 17:28 UTC, nickmccurdy commented on docs/example-formik.md
> +  const mockedOnSubmit = jest.fn()
Let's name this `handleSubmit` to follow React's naming convention for matched `on*` and `handle*` props.

2020-11-24 21:32 UTC, merged

2020-11-26 20:17 UTC, luistak commented
Hey thank you @nickmccurdy I was kinda busy these days I'm glad you fixed those comments ❤️