feat: more tsx tabs in RTL setup doc
testing-library/testing-library-docs pull request #828
Opened 2021-05-05 12:48 UTC by Liadshiran

As proposed in #696 and started with #700, I added the rest of the code snippets examples in Typescript for the Setup doc of react testing library.

2021-07-05 17:56 UTC, pedroapfilho commented
Could you check these conflicts @Liadshiran

2021-07-06 07:41 UTC, MatanBobi requested changes

2021-07-06 07:41 UTC, MatanBobi commented on docs/react-testing-library/setup.mdx
> +import { Omit } from 'react-redux'
I'm not sure about the `Omit` here.. I think that the options type should be different as it's the options for our `render` function.

2021-07-06 07:41 UTC, MatanBobi commented
Thanks for taking the time @Liadshiran!
I left one comment :)

2021-07-06 07:46 UTC, MatanBobi commented
And also, [here](https://github.com/testing-library/testing-library-docs/pull/828/files#diff-9a8513ec98fb23892fc832ebf723cc61ff3844a81e7b37f2a52d997426bb898cR100)
I think we should also omit `wrapper`..

2021-07-06 08:04 UTC, Liadshiran commented
I added `wrapper` and removed `queries` which seemed redundant from the Omit type

2021-07-06 08:06 UTC, MatanBobi approved these changes

2021-07-06 08:11 UTC, merged

2021-07-06 08:11 UTC, MatanBobi commented
Thanks @Liadshiran and @pedroapfilho! :)