Add note about Mocha's watch mode
testing-library/testing-library-docs pull request #887
Opened 2021-07-16 19:24 UTC by jankalfus

The docs currently say that auto cleanup is run automatically if `afterEach` global is present. That is true, however, that doesn't work in Mocha's watch mode, as it executes only the changed files. Globals are not re-run in watch mode. Figuring this out took me an hour or two, so I'm proposing to add info about it to the docs, as I believe it can be helpful for others.

2021-07-20 18:00 UTC, nickmccurdy approved these changes

2021-07-20 18:00 UTC, nickmccurdy commented
This looks good, but would it possibly be simpler if we exposed a hook like this in Testing Library?

2021-07-21 16:57 UTC, jankalfus commented
It might be :) Then on the other hand, this might make folks see what's going on and why it's needed. Anyway, I'll open up a PR with a hook in Testing Library, link it to this one, and we can decide then.

2021-07-24 13:02 UTC, jankalfus commented
Created a PR with a hook in Testing Library: https://github.com/testing-library/react-testing-library/pull/945

2021-08-10 15:17 UTC, eps1lon requested changes
Much appreciated. We don't want to extend the library with support for more test runners at the moment. A documentation only change is sufficient for now.

2021-08-16 07:33 UTC, jankalfus commented
That was my initial thought as well. Reverted.

2021-08-16 09:58 UTC, eps1lon approved these changes

2021-08-16 09:58 UTC, merged

2021-08-16 09:59 UTC, eps1lon commented
Thanks!

@all-contributors add @jankalfus for docs

2021-11-15 01:23 UTC, tassoevan commented
It wasn't immediately obvious for me that this advice was at the "Setup" section because I've read about `cleanup` in the "API" one. As there is a remark about it being automatically called in some testing frameworks, could it be useful to link this note as a small observation?