Update relative imports CRA note
testing-library/testing-library-docs pull request #979
Opened 2021-12-31 10:55 UTC by artivilla

Jest test files without using relative imports in CRA in now allowed with the ability to configure [absolute imports](https://create-react-app.dev/docs/importing-a-component/#absolute-imports). Removing note section.

2021-12-31 11:32 UTC, MatanBobi requested changes
Thanks for this :)

Maybe it will be best to say that this option is available in CRA from version 5 only and refer to the link you attached?

2022-01-04 00:54 UTC, artivilla commented
@MatanBobi I think this feature was introduced as of [v3.3.0](https://github.com/facebook/create-react-app/blob/main/CHANGELOG-3.x.md#330-2019-12-04). See related PRS:
https://github.com/facebook/create-react-app/pull/7822

I can' t tell the exact version however.

2022-01-12 15:18 UTC, MatanBobi approved these changes
Thanks for this @artivilla! :)

2022-01-12 15:19 UTC, merged

2022-01-12 15:19 UTC, MatanBobi commented
@all-contributors please add @artivilla for docs :)